### PR TITLE
Add support for clojurescript

### PR DESCRIPTION
**Pull request by Frozenlock**
As foreshadowed in https://github.com/rm-hull/infix/issues/28, this should make `jasentaa` clojurescript compatible.

The doc files are no longer a direct copy of the worked examples, but I wasn't sure if it was worth the additional visual clutter (reader conditionals) so I left them as they were.

### CODE REVIEW

**Comment by Frozenlock** [comment]
Thanks! I'll start working on Infix to see if I can port it to clojurescript as well.

**Comment by rm-hull** [comment]
It builds on travis ok, but locally it fails for me running `lein test` with a cleaned target directory ... seen this before ?

<details>
<summary>clojure.lang.ExceptionInfo: failed compiling file:target/out/clojure/core/rrb_vector/trees.cljs {:file #object[java.io.File 0x7fc998ef "target/out/clojure/core/rrb_vector/trees.cljs"]}</summary>
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at cljs.compiler$compile_file$fn__3702.invoke(compiler.cljc:1562)
	at cljs.compiler$compile_file.invokeStatic(compiler.cljc:1522)
	at cljs.compiler$compile_file.invoke(compiler.cljc:1498)
	at cljs.closure$compile_file.invokeStatic(closure.clj:573)
	at cljs.closure$compile_file.invoke(closure.clj:564)
	at cljs.closure$fn__5124.invokeStatic(closure.clj:653)
	at cljs.closure$fn__5124.invoke(closure.clj:647)
	at cljs.closure$fn__5052$G__5045__5059.invoke(closure.clj:521)
	at cljs.closure$compile_from_jar.invokeStatic(closure.clj:621)
	at cljs.closure$compile_from_jar.invoke(closure.clj:610)
	at cljs.closure$fn__5128.invokeStatic(closure.clj:663)
	at cljs.closure$fn__5128.invoke(closure.clj:647)
	at cljs.closure$fn__5052$G__5045__5059.invoke(closure.clj:521)
	at cljs.closure$compile_sources$iter__5250__5254$fn__5255.invoke(closure.clj:1011)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:706)
	at clojure.core$next__5108.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3134)
	at clojure.core$doall.invokeStatic(core.clj:3140)
	at clojure.core$doall.invoke(core.clj:3140)
	at cljs.closure$compile_sources.invokeStatic(closure.clj:1007)
	at cljs.closure$compile_sources.invoke(closure.clj:996)
	at cljs.closure$build.invokeStatic(closure.clj:2817)
	at cljs.closure$build.invoke(closure.clj:2718)
	at cljs.build.api$build.invokeStatic(api.clj:208)
	at cljs.build.api$build.invoke(api.clj:189)
	at cljs.build.api$build.invokeStatic(api.clj:195)
	at cljs.build.api$build.invoke(api.clj:189)
	at user$eval3338.invokeStatic(form-init14357386938895469714.clj:1)
	at user$eval3338.invoke(form-init14357386938895469714.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Wrong number of args (1) passed to: nodes/ranges at line 25 target/out/clojure/core/rrb_vector/trees.cljs {:file "target/out/clojure/core/rrb_vector/trees.cljs", :line 25, :column 24, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invokeStatic(core.clj:4739)
	at clojure.core$ex_info.invoke(core.clj:4739)
	at cljs.analyzer$error.invokeStatic(analyzer.cljc:697)
	at cljs.analyzer$error.invoke(analyzer.cljc:693)
	at cljs.analyzer$macroexpand_1.invokeStatic(analyzer.cljc:3342)
	at cljs.analyzer$macroexpand_1.invoke(analyzer.cljc:3338)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3375)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_let_binding_init.invokeStatic(analyzer.cljc:1870)
	at cljs.analyzer$analyze_let_binding_init.invoke(analyzer.cljc:1868)
	at cljs.analyzer$analyze_let_bindings_STAR_.invokeStatic(analyzer.cljc:1890)
	at cljs.analyzer$analyze_let_bindings_STAR_.invoke(analyzer.cljc:1879)
	at cljs.analyzer$analyze_let_bindings.invokeStatic(analyzer.cljc:1921)
	at cljs.analyzer$analyze_let_bindings.invoke(analyzer.cljc:1920)
	at cljs.analyzer$analyze_let.invokeStatic(analyzer.cljc:1936)
	at cljs.analyzer$analyze_let.invoke(analyzer.cljc:1931)
	at cljs.analyzer$fn__1840.invokeStatic(analyzer.cljc:1957)
	at cljs.analyzer$fn__1840.invoke(analyzer.cljc:1955)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3378)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$fn__1654$fn__1660.invoke(analyzer.cljc:1363)
	at cljs.analyzer$fn__1654.invokeStatic(analyzer.cljc:1363)
	at cljs.analyzer$fn__1654.invoke(analyzer.cljc:1355)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$fn__1654$fn__1660.invoke(analyzer.cljc:1363)
	at cljs.analyzer$fn__1654.invokeStatic(analyzer.cljc:1363)
	at cljs.analyzer$fn__1654.invoke(analyzer.cljc:1355)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$fn__1821.invokeStatic(analyzer.cljc:1849)
	at cljs.analyzer$fn__1821.invoke(analyzer.cljc:1845)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_let_body_STAR_.invokeStatic(analyzer.cljc:1924)
	at cljs.analyzer$analyze_let_body_STAR_.invoke(analyzer.cljc:1923)
	at cljs.analyzer$analyze_let_body.invokeStatic(analyzer.cljc:1929)
	at cljs.analyzer$analyze_let_body.invoke(analyzer.cljc:1926)
	at cljs.analyzer$analyze_let.invokeStatic(analyzer.cljc:1945)
	at cljs.analyzer$analyze_let.invoke(analyzer.cljc:1931)
	at cljs.analyzer$fn__1842.invokeStatic(analyzer.cljc:1961)
	at cljs.analyzer$fn__1842.invoke(analyzer.cljc:1959)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3378)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$fn__1654$fn__1660.invoke(analyzer.cljc:1363)
	at cljs.analyzer$fn__1654.invokeStatic(analyzer.cljc:1363)
	at cljs.analyzer$fn__1654.invoke(analyzer.cljc:1355)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$fn__1654$fn__1658.invoke(analyzer.cljc:1362)
	at cljs.analyzer$fn__1654.invokeStatic(analyzer.cljc:1362)
	at cljs.analyzer$fn__1654.invoke(analyzer.cljc:1355)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$fn__1821.invokeStatic(analyzer.cljc:1849)
	at cljs.analyzer$fn__1821.invoke(analyzer.cljc:1845)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3605)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_fn_method_body.invokeStatic(analyzer.cljc:1664)
	at cljs.analyzer$analyze_fn_method_body.invoke(analyzer.cljc:1662)
	at cljs.analyzer$analyze_fn_method.invokeStatic(analyzer.cljc:1685)
	at cljs.analyzer$analyze_fn_method.invoke(analyzer.cljc:1666)
	at cljs.analyzer$analyze_fn_methods_pass2_STAR_$fn__1778.invoke(analyzer.cljc:1716)
	at clojure.core$map$fn__5587.invoke(core.clj:2747)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:528)
	at clojure.core$seq__5124.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3125)
	at clojure.core$doall.invokeStatic(core.clj:3140)
	at clojure.core$doall.invoke(core.clj:3140)
	at cljs.analyzer$analyze_fn_methods_pass2_STAR_.invokeStatic(analyzer.cljc:1716)
	at cljs.analyzer$analyze_fn_methods_pass2_STAR_.invoke(analyzer.cljc:1715)
	at cljs.analyzer$analyze_fn_methods_pass2.invokeStatic(analyzer.cljc:1719)
	at cljs.analyzer$analyze_fn_methods_pass2.invoke(analyzer.cljc:1718)
	at cljs.analyzer$fn__1784$fn__1789.invoke(analyzer.cljc:1764)
	at cljs.analyzer$fn__1784.invokeStatic(analyzer.cljc:1764)
	at cljs.analyzer$fn__1784.invoke(analyzer.cljc:1721)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3378)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3607)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$fn__1733$fn__1736.invoke(analyzer.cljc:1541)
	at cljs.analyzer$fn__1733.invokeStatic(analyzer.cljc:1539)
	at cljs.analyzer$fn__1733.invoke(analyzer.cljc:1473)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq_STAR_.invokeStatic(analyzer.cljc:3348)
	at cljs.analyzer$analyze_seq_STAR_.invoke(analyzer.cljc:3346)
	at cljs.analyzer$analyze_seq_STAR__wrap.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$analyze_seq_STAR__wrap.invoke(analyzer.cljc:3351)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3377)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.analyzer$analyze_seq.invokeStatic(analyzer.cljc:3378)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:3355)
	at cljs.analyzer$analyze_form.invokeStatic(analyzer.cljc:3545)
	at cljs.analyzer$analyze_form.invoke(analyzer.cljc:3541)
	at cljs.analyzer$analyze_STAR_.invokeStatic(analyzer.cljc:3595)
	at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:3586)
	at cljs.analyzer$analyze.invokeStatic(analyzer.cljc:3616)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:3598)
	at cljs.compiler$emit_source.invokeStatic(compiler.cljc:1386)
	at cljs.compiler$emit_source.invoke(compiler.cljc:1365)
	at cljs.compiler$compile_file_STAR_$fn__3672.invoke(compiler.cljc:1467)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1285)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1274)
	at cljs.compiler$compile_file_STAR_.invokeStatic(compiler.cljc:1451)
	at cljs.compiler$compile_file_STAR_.invoke(compiler.cljc:1444)
	at cljs.compiler$compile_file$fn__3702.invoke(compiler.cljc:1547)
	... 46 more
Caused by: clojure.lang.ArityException: Wrong number of args (1) passed to: nodes/ranges
	at cljs.analyzer$macroexpand_1_STAR_$fn__2369.invoke(analyzer.cljc:3297)
	at cljs.analyzer$macroexpand_1_STAR_.invokeStatic(analyzer.cljc:3294)
	at cljs.analyzer$macroexpand_1_STAR_.invoke(analyzer.cljc:3281)
	... 321 more
Subprocess failed
</details>

**Comment by Frozenlock** [comment]
I'll take a look.

**Comment by Frozenlock** [comment]
I've got some warnings, but no errors.

```
lein test jasentaa.collections-test

lein test jasentaa.parser.basic-test

lein test jasentaa.parser.combinators-test

lein test jasentaa.position-test

lein test jasentaa.test-helpers

lein test jasentaa.worked-example-1

lein test jasentaa.worked-example-2

Ran 18 tests containing 61 assertions.
0 failures, 0 errors.
Reflection warning, doo/shell.clj:58:21 - reference to field getInputStream can't be resolved.
Reflection warning, doo/shell.clj:59:21 - reference to field getErrorStream can't be resolved.
Reflection warning, doo/shell.clj:69:17 - reference to field destroy can't be resolved.
Reflection warning, doo/shell.clj:78:20 - reference to field waitFor can't be resolved.
Reflection warning, doo/karma.clj:102:3 - call to method write can't be resolved (target class is unknown).
Reflection warning, doo/karma.clj:103:3 - call to method write can't be resolved (target class is unknown).
Reflection warning, doo/karma.clj:105:3 - call to method write can't be resolved (target class is unknown).
WARNING: cljs.core/-, all arguments must be numbers, got [any string] instead. at line 32 /home/frozenlock/clojure/jasentaa/test/jasentaa/worked_example_2.cljc

;; ======================================================================
;; Testing with Rhino:

WARNING: You have $CLASSPATH set, probably by accident.
It is strongly recommended to unset this before proceeding.
Reflection warning, /tmp/form-init3457143832840344671.clj:1:1084 - call to static method invokeStaticMethod on clojure.lang.Reflector can't be resolved (argument types: unknown, java.lang.String, unknown).

Testing jasentaa.parser.basic-test

Testing jasentaa.parser.combinators-test

Testing jasentaa.collections-test

Testing jasentaa.position-test

Testing jasentaa.worked-example-1

Testing jasentaa.worked-example-2

Ran 18 tests containing 61 assertions.
0 failures, 0 errors.
```

What is your java Version?

**Comment by rm-hull** [comment]
```
$ java -version
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

... could explain it!

**Comment by Frozenlock** [comment]
Wow, living on the edge!

I swapped from 8 to 9 and it sill works.

**Comment by rm-hull** [comment]
yeah, ... let's not spend any more effort on this, and tentatively put it down to a java 10 incompatibility somewhere in the stack. 

Does seem to pop up occasionally elsewhere though:

* https://dev.clojure.org/jira/browse/CRRBV-15
* https://github.com/brandonbloom/fipp/issues/42
* https://github.com/emezeske/lein-cljsbuild/issues/469

**Pull request merged**
